import hashlib
import logging
from fnmatch import fnmatch
from pathlib import Path

logger = logging.getLogger(__name__)

# Bytes to sniff from the head of a file when checking for auto-generated
# markers. 2 KB is enough to catch the standard header blocks produced by
# Visual Studio, xsd.exe, svcutil, T4, and protoc without loading large files.
_AUTOGEN_SNIFF_BYTES = 2048

# Substrings that, when present in the first ``_AUTOGEN_SNIFF_BYTES`` of a
# file, mark it as machine-generated. Matching is case-insensitive.
_AUTOGEN_MARKERS = (
    b"<auto-generated",           # Microsoft/Roslyn standard
    b"auto-generated by",         # xsd, svcutil, generic tools
    b"autogenerated by",
    b"generated by the protocol buffer compiler",
    b"@generated",                # Facebook/Meta convention
    b"do not edit this file",     # Common manual marker
    b"do not modify this file",
)


def is_auto_generated(file_path: Path) -> bool:
    """Return True if the file looks machine-generated.

    Checks the first :data:`_AUTOGEN_SNIFF_BYTES` for any of
    :data:`_AUTOGEN_MARKERS`. Read errors are treated as *not* auto-generated
    so a transient I/O failure doesn't silently drop real source files.
    """
    try:
        with file_path.open("rb") as fh:
            head = fh.read(_AUTOGEN_SNIFF_BYTES).lower()
    except OSError:
        return False
    return any(marker in head for marker in _AUTOGEN_MARKERS)

DEFAULT_EXCLUSIONS = frozenset({
    # Language-agnostic
    ".git", "node_modules", "venv", ".venv", "__pycache__",
    "build", "dist", "target",
    "*.min.js", "*.min.css",
    # Java/JVM
    "**/generated-sources/**", "**/migrations/**",
    # .NET / C#
    "obj", "bin", "packages",
    "**/*.Designer.cs",      # WinForms/ASP.NET designer-generated
    "**/*.g.cs", "**/*.g.i.cs",  # Roslyn source generators
    "**/AssemblyInfo.cs",    # Auto-generated assembly metadata
    "**/wwwroot/lib/**",     # ASP.NET third-party JS/CSS
})


def merge_exclusions(user_patterns: list[str] | None) -> frozenset[str]:
    """Combine user-supplied patterns with :data:`DEFAULT_EXCLUSIONS`.

    User patterns are *additive*, never replacing the defaults. This prevents
    callers from accidentally re-enabling ``node_modules`` or ``.git`` scans
    just because they wanted to add one project-specific exclusion.
    """
    if not user_patterns:
        return DEFAULT_EXCLUSIONS
    return frozenset(DEFAULT_EXCLUSIONS | set(user_patterns))


def is_github_url(source: str) -> bool:
    return source.startswith("https://github.com/") or source.startswith("git@github.com:")


def derive_repo_name(source: str) -> str:
    if is_github_url(source):
        path = source.replace("https://github.com/", "").replace("git@github.com:", "")
        path = path.rstrip("/").removesuffix(".git")
        return path
    return Path(source).name


def is_excluded(relative_path: Path, exclusion_patterns: frozenset[str]) -> bool:
    path_str = str(relative_path)
    parts = relative_path.parts
    for pattern in exclusion_patterns:
        if "**" in pattern or "*" in pattern:
            if fnmatch(path_str, pattern):
                return True
            # `fnmatch` doesn't implement real recursive-glob semantics — a
            # pattern like ``**/*.Designer.cs`` requires at least one ``/`` in
            # the input, so root-level files (``Foo.Designer.cs``) slip
            # through. Strip a leading ``**/`` and retry so the pattern also
            # matches repo-root files.
            if pattern.startswith("**/") and fnmatch(path_str, pattern[3:]):
                return True
        else:
            if pattern in parts:
                return True
    return False


def compute_file_hash(file_path: Path) -> str:
    h = hashlib.md5()
    h.update(file_path.read_bytes())
    return h.hexdigest()


def collect_files(
    root: Path,
    supported_extensions: set[str],
    exclude_patterns: frozenset[str] | None = None,
) -> list[Path]:
    if exclude_patterns is None:
        exclude_patterns = DEFAULT_EXCLUSIONS
    files = []
    skipped_autogen = 0
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix not in supported_extensions:
            continue
        relative = path.relative_to(root)
        if is_excluded(relative, exclude_patterns):
            continue
        if is_auto_generated(path):
            skipped_autogen += 1
            logger.debug("skipping auto-generated file: %s", relative)
            continue
        files.append(path)
    if skipped_autogen:
        logger.info(
            "collector: skipped %d auto-generated file(s) under %s",
            skipped_autogen, root,
        )
    return files
